### ISSUE TITLE
toml.decode hangs

### ISSUE THREAD

**Issue by miccoli** [g-s-k/matlab-toml#12]
As of commit c7900aaa I encountered some examples of strings that can hang `toml.decode`.

```
>> chr = ['a = [', newline, ']']

chr =

    'a = [
     ]'

>> toml.decode(chr)
Operation terminated by user during cell/unique>celluniqueR2012a (line 263)


In cell/unique (line 89)
    [varargout{1:nlhs}] = celluniqueR2012a(varargin{:});

In parsevalue (line 269)
    if numel(unique(contained_types)) > 1

In toml.decode (line 60)
      value_fix = parsevalue(value, force);
```

Expected result is
```
ans = 

  struct with fields:

    a: {}
```

A second example is
```
>> toml.decode('foo')    
Operation terminated by user during parsevalue (line 21)


In toml.decode (line 60)
      value_fix = parsevalue(value, force);
```
Expected results is an Exception, since `'foo'` is not valid toml.

In both cases `toml.decode` got stuck (in an infinite loop?) and I had to break the lock with Ctrl-C.

**Comment by gaetawoo** [comment]
@miccoli I haven't tried to replicate what you've shown here, but have you tried my fork of the repo? Here: [https://github.com/gaetawoo/matlab-toml](https://github.com/gaetawoo/matlab-toml)

I have a pending [Pull Request](https://github.com/g-s-k/matlab-toml/pull/10) with my changes so it is possible what you are showing is already fixed. But it might not be.

**Comment by gaetawoo** [comment]
@miccoli fun times. Thanks for checking. I won't be able to get to it for a bit. The pull request is going to get merged once I populate the requested tests. At that point i can look into this bug. 

Is this a show stopper for you or you just came across a case that broke it?

**Comment by miccoli** [comment]
@gaetawoo Once you now where the problem is you can avoid it easily... so not a big problem for me.
