### ISSUE TITLE
strings getting parsed as dates

### ISSUE THREAD

**Issue by jrmxn** [g-s-k/matlab-toml#18]
Thanks for making this public, it's been nice to use. 

Encountering the following issue - trying to read a toml file with the following content:
`data_files = ["2022-05-12_rx_t2s001", "2022-05-12_rx_t1s001"]`
Where these are file names. But the decode function is trying to load these as dates. I didn't see an obvious escape feature in parsevalue.m

I am probably not the only one that follows iso8601 when naming files - so figure this should not be the default behavior. 

Probably the whole value should match a datetime structure (rather than it just containing a datetime structure)?

Thanks!

Output:
Error using datetime
Unable to convert '["2022-05-12_rnn_t2s001", "2022-05-12_rnn_t1s001"]' to datetime using the format 'yyyy-MM-dd'.
Error in parsevalue (line 83)
    val = datetime(trimmed_val, 'InputFormat', fmt_str);
Error in toml.decode (line 60)
      value_fix = parsevalue(value, force);

**Comment by g-s-k** [comment]
Hi! Thanks for the report. I am currently rewriting the library (#14) and it seems to work well in that branch. I will ping you once it is ready to merge 😄

**Comment by g-s-k** [comment]
@jrmxn The new version is merged now, with a test case to ensure this works. Just FYI, there is a breaking change described in [the release notes](https://github.com/g-s-k/matlab-toml/releases/tag/v1.0.0). Cheers!
