### ISSUE TITLE
fileread error

### ISSUE THREAD

**Issue by jrmxn** [g-s-k/matlab-toml#19]
Just pulled the master branch, getting the following issue:

```
Error using toml.read
Error: File: read.m Line: 12 Column: 43
Incorrect use of '=' operator. To assign a value to a variable, use '='. To compare values for equality, use '=='.
```
Line 12 is:
`raw_text = fileread(filename, Encoding="UTF-8");`
which is maybe python?

Replacing with the following seems to do the trick:
```
file = fopen(filename,'r','n','UTF-8');
raw_text = fread(file, [1 inf], '*char');
```

Thanks!

**Comment by g-s-k** [comment]
Ah! I copied that out of the `fileread` docs (I don't have access to proper MATLAB). I will try your solution.
