### ISSUE TITLE
Adding an struct_to_map function to the repository

### ISSUE THREAD

**Issue by suvimh** [g-s-k/matlab-toml#26]
Hi, 

I was having some trouble getting the write function to format the toml properly for nested structures so I wrote a function that is the inverse of the map_to_struct function. I personally find it easier to read the file, convert the map into a struct that I could modify and then convert it back to a map, so that the formatting definitely remains the same when writing any changes to the file. 

I was wondering whether this would be useful addition to the repository itself? I have the code and can put in a pull request if so.

**Comment by g-s-k** [comment]
Sure! I would be happy to take a look at what you have and include it, if it would help others use the library.

**Comment by suvimh** [comment]
Alright! I added a pull request now for it. 
https://github.com/g-s-k/matlab-toml/pull/27
Let me know if you update the repo and I switch to use it instead of including the function in my own code.
