### ISSUE TITLE
toml.encode/decode do not properly quote/unquote backslashes

### ISSUE THREAD

**Issue by miccoli** [g-s-k/matlab-toml#4]
`toml.encode` does not properly escapes backslashes in strings.

When encoding:
```
>> s = struct('a', 'A\B');
>> t = toml.encode(s);
>> display(t)

t =

    'a = "A\B"
     '
```
but it should be `t = 'a = "A\\B"'`

When decoding:
```
>> t = 'a = "A\\B"';
>> s = toml.decode(t);
Error using parsevalue (line 193)
Invalid escape sequence: \B

Error in toml.decode (line 60)
      value_fix = parsevalue(value, force);
``` 

and also the roundtrip does not work:
```
>> s = struct('a', 'A\B');
>> toml.decode(toml.encode(s))
Error using parsevalue (line 193)
Invalid escape sequence: \B

Error in toml.decode (line 60)
      value_fix = parsevalue(value, force);
```

**Comment by gaetawoo** [comment]
if you import from a TOML file, using string literal with single quotes does transmit the single (or any) backslash properly. As far as basic strings where escaped characters can exist... there is something wrong with the regex on [Line 191](https://github.com/g-s-k/matlab-toml/blob/c7900aaa757a97ef977c27670e49414a2443bfee/%2Btoml/private/parsevalue.m#L191) of `parsevalue.m`. It should find the first `\` and look at the next character. What it does now, is finds the first `\` and then sees another `\` behind it, thinks.. _ok that's fine_ and then decides it finds the second `\` (which was part of the first `\` sequence) and sees there is an invalid character behind it. It should have stopped at the second `\` and not considered anything else beyond that.

I'm not currently sure how to fix it but it's a regex thing.

**Comment by gaetawoo** [comment]
@miccoli 	Ok I have a solution, I'll be submitting a pull request later.

I have a deleteme.TOML file as an input with the following contents:
```
a = "A\\ \" B"
b = "A\nB"
c = "this \t is my \u0610 last \\ big \\resort"
```
Now I run the following commands and get the following outputs:
```
>> a = toml.read('deleteme.toml')
a = 
  struct with fields:

    a: 'A\ " B'
    b: 'A↵B'
    c: 'this → is my ؐ last \ big \resort'
>> toml.encode(a)
ans =
    'a = "A\\ \" B"
     b = "A\nB"
     c = "this \t is my \u0610 last \\ big \\resort"'
```
The lack of correct parsing was due to insufficient regex. The lack of escaping on the encoding was due to not having any string replacement to apply the escape to the common characters. The extra line at the end of your test was because the final result wasn't trimmed for whitespace.

If I test nested keys:
The input TOML has the following:
```
a = "A\\ \" B"
b.a = "A\nB"
b.b = "Nested \t Test \U0400"
c = "this \t is my \u0610 last \\ big \\resort"
```
The round-trip in MATLAB is the following:
```
>> a = toml.read('deleteme.toml')
a = 
  struct with fields:

    a: 'A\ " B'
    b: [1×1 struct]
    c: 'this → is my ؐ last \ big \resort'
>> a.b
ans = 
  struct with fields:

    a: 'A↵B'
    b: 'Nested → Test Ѐ'
>> toml.encode(a)
ans =
    'a = "A\\ \" B"
     c = "this \t is my \u0610 last \\ big \\resort"
     [b]
     a = "A\nB"
     b = "Nested \t Test Ѐ"'
```
